# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Information
title: Trigger's Tools & Games (but mostly tools)
author: Robert Jordan
email: triggerstools@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A personal blog and source of information for trigger_segfault's tools and other
  projects that don't already have dedicated pages. I'm a developer that's fluent with
  C#, C/C++, Java, and ActionScript, and a bit of Python, although I spend most
  of my time working in C#.
tags: [trigger_death,trigger_segfault,trigger,robert,jordan,game,program,programming,tool,development]
theme_color: "#00C6D8"

# Contacts
github_username: trigger-segfault
reddit_username: trigger_segfault
steam_username: trigger_segfault
steam_url: trigger_death
discord_name: trigger_development
discord_invite: https://discord.gg/vB7jUbY
youtube_channel_name: trigger_segfault
youtube_channel: UCGQ4ksvfuzCeVbDplBc5yhg
twitter_username: triggersegfault
mal_username: trigger_segfault
anilist_username: triggersegfault
vndb_username: triggersegfault
vndb_userid: 162862
mfc_username: trigger_segfault
linkedin_username: robert-g-jordan

# Settings
url: "https://trigger-segfault.github.io" # the base hostname & protocol for your site, e.g. http://example.com
show_excerpts: true # Show summaries on blog listings
google_analytics: UA-129364070-1

# Navbars
header_pages: # extensions are not required, both .md and .html pages will be searched for
  - home
  - blog
  - tools
  - games
  - mods
  - libraries
  - anime
  - resume

rct2tools_header_pages:
  - tools/rct2-tools/rct2-tools.html
  - tools/rct2-tools/content-browser.html
  - tools/rct2-tools/graphics-extractor.html
  - tools/rct2-tools/group-creator.html
  - tools/rct2-tools/water-creator.html
  - tools/rct2-tools/maze-generator.html
  - tools/rct2-tools/music-manager.html
  - tools/rct2-tools/audio-extractor.html
  #- tools/rct2-tools/openrct2-stub.html

defaults:
  -
    scope:
      path: ""
    values:
      title_postfix: Trigger's Tools & Games
      image: /assets/icon-256.png
      tags: [trigger_death,trigger_segfault,trigger,robert jordan,game,program,programming,tool,development]
  -
    scope:
      path: "tools/rct2-tools"
    values:
      layout: "rct2-tools"
      title_postfix: Trigger's RCT2 Tools
      image: /tools/rct2-tools/assets/icon-256.png
      tags: [trigger_death,trigger_segfault,trigger,robert jordan,rct2,rollercoaster,tycoon,2,openrct2]
  -
    scope:
      path: "mods/trigger-cookies"
    values:
      layout: "trigger-cookies"
      title_postfix: An outdated Cookie Clicker mod
      image: /mods/trigger-cookies/assets/icon-256.png
      tags: [trigger_death,trigger_segfault,trigger,robert jordan,cookies,triggercookies,cookie,clicker,mod]

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

feed:
  categories:
    - anime
    - dev
    - gaming
    - meta
    - music
    - personal

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from

# Run settings
host: 0.0.0.0 # Allow access from other devices on the LAN for testing
              # Unfortunately this breaks redirects among other things! >:(

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/ts/
  - serve.cmd
  - serve.ps1
  - trigger-segfault.code-workspace
  - tsconfig.json
